# The workflow checks that all the jobs and services required for 
# memcached to start are here.

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf-memcached
spec:
  entrypoint: wf-memcached
  # serviceAccountName: memcached-memcached
  serviceAccountName: keystone-api
  templates:
  - name: wf-memcached
    steps:
    - - name: svc-memcached
        template: svc-memcached

  - name: svc-memcached
    resource:
      action: get
      # Really boggus. Doesn't check if service actually operational
      successCondition: metadata.name == memcached
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: memcached
