# The workflow checks that all the jobs and services required for 
# keystone-api to start are here.

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf-keystone-api
spec:
  entrypoint: wf-keystone-api
  serviceAccountName: wf-keystone-sa
  volumes:
  {{- include "keystone.templates.steps._bootstrap.volumes" . | nindent 2 }}
  {{- include "keystone.templates.steps._credential_setup.volumes" . | nindent 2}}
  {{- include "keystone.templates.steps._db_init.volumes" . | nindent 2}}
  {{- include "keystone.templates.steps._db_sync.volumes" . | nindent 2}}
  {{- include "keystone.templates.steps._domain_manage.volumes" . | nindent 2}}
  {{- include "keystone.templates.steps._fernet_setup.volumes" . | nindent 2}}
  {{- include "keystone.templates.steps._rabbit_init.volumes" . | nindent 2}}

  templates:
  - name: wf-keystone-api
    dag:
      tasks:
      - name: svc-memcached
        template: svc-memcached
      - name: svc-mariadb
        template: svc-mariadb
      - name: svc-rabbitmq
        template: svc-rabbitmq
      - name: job-keystone-db-init
        template: job-keystone-db-init
        dependencies:
        - svc-mariadb
      - name: job-keystone-rabbit-init
        template: job-keystone-rabbit-init
        dependencies:
        - svc-rabbitmq
      - name: job-keystone-db-sync
        template: job-keystone-db-sync
        dependencies:
        - job-keystone-db-init
        - job-keystone-rabbit-init
      - name: job-keystone-credential-setup
        template: job-keystone-credential-setup
        dependencies:
        - job-keystone-db-sync
      - name: job-keystone-fernet-setup
        template: job-keystone-fernet-setup
        dependencies:
        - job-keystone-db-sync
      - name: svc-keystone-api
        template: svc-keystone-api
        dependencies:
          - job-keystone-credential-setup
          - job-keystone-fernet-setup

  - name: svc-memcached
    resource:
      action: get
      # Really boggus. Doesn't check if service actually operational
      successCondition: metadata.name == memcached
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: memcached

  - name: svc-mariadb
    resource:
      action: get
      # Really boggus. Doesn't check if service actually operational
      successCondition: metadata.name == mariadb
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: mariadb

  - name: svc-rabbitmq
    resource:
      action: get
      # Really boggus. Doesn't check if service actually operational
      successCondition: metadata.name == rabbitmq
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: rabbitmq

  - name: svc-keystone-api
    resource:
      action: get
      # Really boggus. Doesn't check if service actually operational
      successCondition: metadata.name == keystone-api
      manifest: |
        apiVersion: v1
        kind: Service
        metadata:
          name: keystone-api

  - name: job-keystone-db-sync
    container:
    {{- include "keystone.templates.steps._db_sync.container" . | nindent 6 }}

  - name: job-keystone-db-init
    container:
    {{- include "keystone.templates.steps._db_init.container" . | nindent 6 }}

  - name: job-keystone-credential-setup
    container:
    {{- include "keystone.templates.steps._credential_setup.container" . | nindent 6 }}

  - name: job-keystone-fernet-setup
    container:
    {{- include "keystone.templates.steps._fernet_setup.container" . | nindent 6 }}

  - name: job-keystone-rabbit-init
    container:
    {{- include "keystone.templates.steps._rabbit_init.container" . | nindent 6 }}
